# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c0a1093ba8ac698df35ae9604a4e37a2f588b6b3b80a038f9b2e29237514255018903ff862e206595316a0e207de64aa9d78588f2e10f6da0f9ba2c795c1d3

test:
  secret_key_base: 2d69373d8ab54428d2aaa15e7898a72e47e2fcc22a74a89004c81be9d9b0f6656b857b1f38f724b2e4771ef5c3b8b31bc74badbb8db93221fd0ebc9fda6e733b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
